# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'baidumapsdk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'BaiduMapKit', "~> 3.4.0"

  # Pods for baidumapsdk

  target 'baidumapsdk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'baidumapsdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
